import Head from "next/head";
import styles from "@/styles/Home.module.css";
import VerticalTextConverter from "@/components/VerticalTextConverter";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>瞬間❗️縦書きくん</title>
        description:
        '文章や文字列を一瞬で縦書きにします。',
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.topAd}>
        <a href="https://px.a8.net/svt/ejp?a8mat=3TLRSP+B0IPO2+407E+691UP">
          <img
            src="https://www28.a8.net/svt/bgt?aid=231123193666&wid=001&eno=01&mid=s00000018689001050000&mc=1"
            alt="広告の説明"
          />
        </a>
      </div>
      <main className={styles.main}>
        <div className={styles.wrapper}>
          <h1 className={styles.title}>
            <Image
              src="/tategaki_main.png"
              alt="たてがきくん"
              width={500}
              height={250}
            />
          </h1>
          <div className={styles.container}>
            <h3>〜使い方〜</h3>
            <ol>
              <li>文字を入力します</li>
              <li>コピーします</li>
            </ol>
          </div>
          {/* 広告3 */}
          <div style={{ marginTop: "40px" }}>
            <a
              href="https://px.a8.net/svt/ejp?a8mat=3TLRSP+B0IPO2+407E+65U41"
              rel="nofollow"
            >
              <img
                border="0"
                width="300"
                height="250"
                alt=""
                src="https://www26.a8.net/svt/bgt?aid=231123193666&wid=001&eno=01&mid=s00000018689001035000&mc=1"
              />
            </a>
            <img
              border="0"
              width="1"
              height="1"
              src="https://www15.a8.net/0.gif?a8mat=3TLRSP+B0IPO2+407E+65U41"
              alt=""
            ></img>
          </div>
          {/* 広告3おわり */}

          <VerticalTextConverter />
        </div>
        {/* 広告1 */}
        <a
          href="https://px.a8.net/svt/ejp?a8mat=3TLR08+D0K5V6+2PEO+1HUVDT"
          rel="nofollow"
        >
          <img
            border="0"
            width="320"
            height="50"
            alt=""
            src="https://www22.a8.net/svt/bgt?aid=231122168787&wid=001&eno=01&mid=s00000012624009046000&mc=1"
          />
        </a>
        <img
          border="0"
          width="1"
          height="1"
          src="https://www12.a8.net/0.gif?a8mat=3TLR08+D0K5V6+2PEO+1HUVDT"
          alt=""
        ></img>

        {/* 広告2 */}
        <a
          href="https://px.a8.net/svt/ejp?a8mat=3TLR08+D0K5V6+2PEO+1I4QBL"
          rel="nofollow"
        >
          <img
            border="0"
            width="300"
            height="250"
            alt=""
            src="https://www28.a8.net/svt/bgt?aid=231122168787&wid=001&eno=01&mid=s00000012624009092000&mc=1"
          />
        </a>
        <img
          border="0"
          width="1"
          height="1"
          src="https://www14.a8.net/0.gif?a8mat=3TLR08+D0K5V6+2PEO+1I4QBL"
          alt=""
        ></img>
      </main>
    </>
  );
}
